### PR TITLE
Update versions to 2.0.0

### PR DESCRIPTION
**Pull request by msujew**
Updates the version information for releasing version 2.0.0.

### CODE REVIEW

**Comment by Lotes** [comment]
Are you adding the `package-lock.json` as a last commit?

**Comment by Lotes** [comment]
Another thing: If you are searching for "/langium/langium": there are a lot of links that are using the old web link. Could be a separate PR, I think. Mostly the change logs. But also comments in code or within READMEs

**Comment by msujew** [comment]
@Lotes Right, forgot about the `package-lock.json`.

But yeah, we can do the readme update in a separate PR. Especially since GitHub does link forwarding for us, so it's not urgent.

**Comment by Lotes** [comment]
> Are you adding the `package-lock.json` as a last commit?

Sorry, I jumped over it.

**Review by spoenemann — APPROVED** [review]
Thanks!

**Pull request merged**
