### PR TITLE
langium/lsp: Added 'getReferenceCandidates(...)' hook to 'DefaultCompletionProvider'

### PR DESCRIPTION
**Pull request by sailingKieler**
… allowing to add the completion-specific scope computation refinements.

### CODE REVIEW

**Review by spoenemann — COMMENTED** [review]
I think this makes sense and I confirm that it has been often useful in Xtext.

Thought: shall the template method also include the call to `scope.getAllElements()`? That means it would return a Stream, making it very easy to filter elements from the scope without the need to manipulate the scope hierarchy.

**Comment by sailingKieler** [comment]
> Thought: shall the template method also include the call to scope.getAllElements()? That means it would return a Stream, making it very easy to filter elements from the scope without the need to manipulate the scope hierarchy.

Hmm ... I don't have strong opinion here, we could do that yes.

In my case I only manipulated the `ReferenceInfo` depending on some conditions wrt. the `CompetionContext`, and then delegated to the scope provider and returned its result.

We could also take `{ getAllElements: () => Stream<AstNodeDescription> }` as return type.
Then a `Scope` would be a valid result, but something like the following is also possible.

```
    const scope = this.scopeProvider.getScope(refInfo);
    .
    .
    .
    return {
        getAllElements: () => scope.getAllElements().filter(e => ... ),
    };
```

**Comment by sailingKieler** [comment]
You may be right, but then we need a better template method name.

**Review by spoenemann — APPROVED** [review]
Looks good! I totally overlooked that we already had `filterCrossReference`, but the new API is better IMO, unifying the two template methods into one.

**Pull request merged**
