### PR TITLE
fix: multiple document-builder listeners

### LINKED ISSUE #1740: Code Completion hangs
### Discussed in https://github.com/eclipse-langium/langium/discussions/1737

<div type='discussions-op-text'>

<sup>Originally posted by **cdietrich** November  4, 2024</sup>
we sometimes face the situation that the code completion "hangs" forever like this

Bildschirmfoto 2024-11-04 um 13 19 40

is it possible the completion is waiting "forever" for the build? e.g waitUntilPhase(Indexed) never finishes?

mixture of manual editing and then invoking content assist</div>

### PR DESCRIPTION
**Pull request by cdietrich**
Closes #1740

### CODE REVIEW

**Review by msujew — APPROVED** [review]
Thanks for the investigation and the fix. I'll likely release a new patch version of Langium (3.2.1) that contains this change in the afternoon 👍

**Comment by msujew** [comment]
@cdietrich 3.2.1 is online :)

**Comment by cdietrich** [comment]
@msujew can you please also push a tag

**Comment by msujew** [comment]
@cdietrich Done

**Pull request merged**
